services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: task_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d task_manager_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: nestjs_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:pass@db:5432/task_manager_db?schema=public"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: